import type {
  AgentEvent,
  AgentEventStatus,
  AgentEventType,
  AgentLocation,
} from "./types";

const runId = "run-smallville-day-001";
const taskId = "task-smallville-town-projection";
const baseTimestamp = "2026-07-04T14:";

const agents = {
  isabella: {
    agentId: "agent-isabella",
    agentName: "Isabella",
    agentRole: "planner",
  },
  klaus: {
    agentId: "agent-klaus",
    agentName: "Klaus",
    agentRole: "researcher",
  },
  maria: {
    agentId: "agent-maria",
    agentName: "Maria",
    agentRole: "coder",
  },
  sam: {
    agentId: "agent-sam",
    agentName: "Sam",
    agentRole: "reviewer",
  },
  mei: {
    agentId: "agent-mei",
    agentName: "Mei",
    agentRole: "memory",
  },
} as const;

type AgentKey = keyof typeof agents;

type FixtureEvent = {
  sequence: number;
  agent: AgentKey;
  type: AgentEventType;
  summary: string;
  content: string;
  locationHint: AgentLocation;
  subLocationId: string;
  activity: string;
  routinePhase: "morning" | "midday" | "afternoon" | "evening";
  targetAgentId?: string;
  targetTaskId?: string;
  toolName?: string;
  toolInput?: unknown;
  toolOutputSummary?: string;
  artifactIds?: string[];
  status?: AgentEventStatus;
};

function timestamp(sequence: number): string {
  return `${baseTimestamp}${String(sequence).padStart(2, "0")}:00.000Z`;
}

function makeEvent(input: FixtureEvent): AgentEvent {
  const agent = agents[input.agent];

  return {
    id: `smallville-${String(input.sequence).padStart(3, "0")}`,
    runId,
    taskId,
    timestamp: timestamp(input.sequence),
    sequence: input.sequence,
    ...agent,
    type: input.type,
    content: input.content,
    summary: input.summary,
    targetAgentId: input.targetAgentId,
    targetTaskId: input.targetTaskId,
    toolName: input.toolName,
    toolInput: input.toolInput,
    toolOutputSummary: input.toolOutputSummary,
    artifactIds: input.artifactIds,
    locationHint: input.locationHint,
    status: input.status ?? "running",
    metadata: {
      source: "mock",
      tags: ["smallville-day", input.routinePhase, input.subLocationId],
      subLocationId: input.subLocationId,
      activity: input.activity,
      routinePhase: input.routinePhase,
    },
  };
}

export const mockSmallvilleDayRun: AgentEvent[] = [
  makeEvent({
    sequence: 0,
    agent: "isabella",
    type: "thinking",
    summary: "Wake and scan the day plan",
    content: "Isabella starts the day by checking the town planning table.",
    locationHint: "town_hall",
    subLocationId: "town_hall_table",
    activity: "reads daily plan",
    routinePhase: "morning",
  }),
  makeEvent({
    sequence: 1,
    agent: "isabella",
    type: "memory_read",
    summary: "Recall yesterday's blocker",
    content: "Isabella recalls that the review evidence wall needs a fresh note.",
    locationHint: "archive",
    subLocationId: "archive_shelves",
    activity: "recalls blocker",
    routinePhase: "morning",
  }),
  makeEvent({
    sequence: 2,
    agent: "isabella",
    type: "decision",
    summary: "Prioritize evidence before polish",
    content: "Isabella decides that the town should prove behavior before decoration.",
    locationHint: "town_hall",
    subLocationId: "town_hall_office",
    activity: "sets priority",
    routinePhase: "morning",
  }),
  makeEvent({
    sequence: 3,
    agent: "isabella",
    type: "handoff",
    summary: "Ask Klaus for morning research",
    content: "Isabella routes a research task through the dispatch queue.",
    locationHint: "dispatch_board",
    subLocationId: "dispatch_queue",
    activity: "dispatches task",
    routinePhase: "morning",
    targetAgentId: agents.klaus.agentId,
    targetTaskId: "task-research-town-routine",
  }),
  makeEvent({
    sequence: 4,
    agent: "klaus",
    type: "thinking",
    summary: "Read the stacks",
    content: "Klaus reviews prior town projection notes at the library stacks.",
    locationHint: "library",
    subLocationId: "library_stacks",
    activity: "reads notes",
    routinePhase: "morning",
  }),
  makeEvent({
    sequence: 5,
    agent: "klaus",
    type: "memory_read",
    summary: "Find Smallville constraint",
    content: "Klaus reads that visual spaces cannot own runtime facts.",
    locationHint: "library",
    subLocationId: "library_stacks",
    activity: "extracts rule",
    routinePhase: "morning",
  }),
  makeEvent({
    sequence: 6,
    agent: "klaus",
    type: "message",
    summary: "Tell Maria to keep assets passive",
    content: "Klaus tells Maria to treat interiors as projection anchors only.",
    locationHint: "library",
    subLocationId: "library_reading_nook",
    activity: "shares rule",
    routinePhase: "morning",
    targetAgentId: agents.maria.agentId,
  }),
  makeEvent({
    sequence: 7,
    agent: "maria",
    type: "tool_call",
    summary: "Assemble the workbench sprites",
    content: "Maria uses the workshop bench to bind original sprites to stable zones.",
    locationHint: "workshop",
    subLocationId: "workshop_bench",
    activity: "assembles sprites",
    routinePhase: "morning",
    toolName: "generate_assets",
    toolInput: { assetSet: "agent-town-v1" },
    toolOutputSummary: "Project-authored map and sprites generated.",
    artifactIds: ["asset-town-v1"],
  }),
  makeEvent({
    sequence: 8,
    agent: "maria",
    type: "memory_write",
    summary: "Record asset boundary",
    content: "Maria records that source assets are generated by this repository.",
    locationHint: "archive",
    subLocationId: "archive_writing_desk",
    activity: "records license",
    routinePhase: "morning",
    artifactIds: ["asset-license-note"],
  }),
  makeEvent({
    sequence: 9,
    agent: "sam",
    type: "thinking",
    summary: "Prepare review pass",
    content: "Sam opens the review table and plans a boundary check.",
    locationHint: "review_room",
    subLocationId: "review_table",
    activity: "prepares review",
    routinePhase: "midday",
  }),
  makeEvent({
    sequence: 10,
    agent: "sam",
    type: "message",
    summary: "Request evidence from Isabella",
    content: "Sam asks Isabella to bring proof to the evidence wall.",
    locationHint: "review_room",
    subLocationId: "review_evidence_wall",
    activity: "requests proof",
    routinePhase: "midday",
    targetAgentId: agents.isabella.agentId,
  }),
  makeEvent({
    sequence: 11,
    agent: "mei",
    type: "memory_read",
    summary: "Read morning memory",
    content: "Mei checks the memory shelves before the town lunch meeting.",
    locationHint: "archive",
    subLocationId: "archive_shelves",
    activity: "reads memory",
    routinePhase: "midday",
  }),
  makeEvent({
    sequence: 12,
    agent: "mei",
    type: "message",
    summary: "Invite Isabella to the cafe",
    content: "Mei invites Isabella to review the daily memory thread at the cafe.",
    locationHint: "square",
    subLocationId: "square_cafe",
    activity: "sets lunch talk",
    routinePhase: "midday",
    targetAgentId: agents.isabella.agentId,
  }),
  makeEvent({
    sequence: 13,
    agent: "isabella",
    type: "handoff",
    summary: "Meet Maria by the fountain",
    content: "Isabella carries the plan from town hall toward the fountain edge.",
    locationHint: "square",
    subLocationId: "square_fountain_edge",
    activity: "meets Maria",
    routinePhase: "midday",
    targetAgentId: agents.maria.agentId,
    targetTaskId: "task-wire-interiors",
  }),
  makeEvent({
    sequence: 14,
    agent: "maria",
    type: "tool_call",
    summary: "Debug interior anchors",
    content: "Maria checks that sub-location anchors resolve without changing facts.",
    locationHint: "workshop",
    subLocationId: "workshop_debug_desk",
    activity: "debugs anchors",
    routinePhase: "midday",
    toolName: "run_projection_check",
    toolInput: { check: "interior-anchor-routing" },
    toolOutputSummary: "Anchors resolve from event metadata to Tiled object targets.",
  }),
  makeEvent({
    sequence: 15,
    agent: "klaus",
    type: "tool_call",
    summary: "Summarize behavior precedent",
    content: "Klaus writes a note at the reading nook about generative-agent routines.",
    locationHint: "library",
    subLocationId: "library_reading_nook",
    activity: "summarizes routine",
    routinePhase: "midday",
    toolName: "write_note",
    toolInput: { topic: "routine-projection" },
    toolOutputSummary: "Routine note ready for review.",
  }),
  makeEvent({
    sequence: 16,
    agent: "isabella",
    type: "message",
    summary: "Ask Sam to review cafe notes",
    content: "Isabella sends Sam the cafe discussion summary.",
    locationHint: "square",
    subLocationId: "square_cafe",
    activity: "shares plan",
    routinePhase: "midday",
    targetAgentId: agents.sam.agentId,
  }),
  makeEvent({
    sequence: 17,
    agent: "sam",
    type: "decision",
    summary: "Accept interior anchor approach",
    content: "Sam accepts the approach because AgentEvent still owns all facts.",
    locationHint: "review_room",
    subLocationId: "review_table",
    activity: "accepts boundary",
    routinePhase: "afternoon",
  }),
  makeEvent({
    sequence: 18,
    agent: "mei",
    type: "tool_call",
    summary: "Write noon memory",
    content: "Mei writes the noon routine handoff into the memory desk.",
    locationHint: "archive",
    subLocationId: "archive_writing_desk",
    activity: "writes memory",
    routinePhase: "afternoon",
    toolName: "memory_append",
    toolInput: { note: "interior anchors are projection targets" },
    toolOutputSummary: "Memory note appended.",
  }),
  makeEvent({
    sequence: 19,
    agent: "klaus",
    type: "handoff",
    summary: "Post the routine note",
    content: "Klaus posts the routine note on the dispatch notice wall.",
    locationHint: "dispatch_board",
    subLocationId: "dispatch_notice_wall",
    activity: "posts notice",
    routinePhase: "afternoon",
    targetAgentId: agents.isabella.agentId,
    targetTaskId: "task-review-routine-note",
  }),
  makeEvent({
    sequence: 20,
    agent: "isabella",
    type: "decision",
    summary: "Approve afternoon loop",
    content: "Isabella approves the afternoon loop from the planning table.",
    locationHint: "town_hall",
    subLocationId: "town_hall_table",
    activity: "approves loop",
    routinePhase: "afternoon",
  }),
  makeEvent({
    sequence: 21,
    agent: "maria",
    type: "message",
    summary: "Ask Klaus to inspect movement",
    content: "Maria asks Klaus whether the movement trail reads clearly.",
    locationHint: "workshop",
    subLocationId: "workshop_bench",
    activity: "shares build",
    routinePhase: "afternoon",
    targetAgentId: agents.klaus.agentId,
  }),
  makeEvent({
    sequence: 22,
    agent: "klaus",
    type: "memory_write",
    summary: "Record movement interpretation",
    content: "Klaus records that trails are projection evidence, not simulation truth.",
    locationHint: "archive",
    subLocationId: "archive_writing_desk",
    activity: "records trail note",
    routinePhase: "afternoon",
  }),
  makeEvent({
    sequence: 23,
    agent: "sam",
    type: "tool_call",
    summary: "Pin review evidence",
    content: "Sam pins the asset and test evidence to the review wall.",
    locationHint: "review_room",
    subLocationId: "review_evidence_wall",
    activity: "pins evidence",
    routinePhase: "afternoon",
    toolName: "review_evidence",
    toolInput: { paths: ["docs/evidence/M5"] },
    toolOutputSummary: "Evidence paths are ready for verification.",
  }),
  makeEvent({
    sequence: 24,
    agent: "mei",
    type: "memory_read",
    summary: "Check afternoon memory",
    content: "Mei confirms the morning and noon notes align.",
    locationHint: "archive",
    subLocationId: "archive_shelves",
    activity: "checks memory",
    routinePhase: "afternoon",
  }),
  makeEvent({
    sequence: 25,
    agent: "isabella",
    type: "tool_call",
    summary: "Publish the town note",
    content: "Isabella publishes the town note at the notice wall.",
    locationHint: "dispatch_board",
    subLocationId: "dispatch_notice_wall",
    activity: "publishes note",
    routinePhase: "afternoon",
    toolName: "publish_notice",
    toolInput: { channel: "town-notice-wall" },
    toolOutputSummary: "Town note posted.",
  }),
  makeEvent({
    sequence: 26,
    agent: "isabella",
    type: "message",
    summary: "Ask Mei for final memory pass",
    content: "Isabella asks Mei to reconcile the day memory.",
    locationHint: "dispatch_board",
    subLocationId: "dispatch_queue",
    activity: "requests memory",
    routinePhase: "evening",
    targetAgentId: agents.mei.agentId,
  }),
  makeEvent({
    sequence: 27,
    agent: "mei",
    type: "handoff",
    summary: "Send memory note to Maria",
    content: "Mei sends the memory note from the writing desk to Maria.",
    locationHint: "archive",
    subLocationId: "archive_writing_desk",
    activity: "routes memory",
    routinePhase: "evening",
    targetAgentId: agents.maria.agentId,
    targetTaskId: "task-evening-polish",
  }),
  makeEvent({
    sequence: 28,
    agent: "maria",
    type: "tool_call",
    summary: "Patch evening polish",
    content: "Maria patches the evening render at the debug desk.",
    locationHint: "workshop",
    subLocationId: "workshop_debug_desk",
    activity: "patches render",
    routinePhase: "evening",
    toolName: "edit_renderer",
    toolInput: { surface: "town projection" },
    toolOutputSummary: "Activity labels and trails render from WorldState.",
  }),
  makeEvent({
    sequence: 29,
    agent: "klaus",
    type: "message",
    summary: "Send Sam final reading note",
    content: "Klaus sends Sam the final reading note from the library nook.",
    locationHint: "library",
    subLocationId: "library_reading_nook",
    activity: "sends note",
    routinePhase: "evening",
    targetAgentId: agents.sam.agentId,
  }),
  makeEvent({
    sequence: 30,
    agent: "sam",
    type: "decision",
    summary: "Accept evidence shape",
    content: "Sam accepts the evening evidence shape at the review table.",
    locationHint: "review_room",
    subLocationId: "review_table",
    activity: "accepts evidence",
    routinePhase: "evening",
  }),
  makeEvent({
    sequence: 31,
    agent: "isabella",
    type: "memory_write",
    summary: "Write final project memory",
    content: "Isabella writes the final day note at the archive writing desk.",
    locationHint: "archive",
    subLocationId: "archive_writing_desk",
    activity: "writes closeout",
    routinePhase: "evening",
  }),
  makeEvent({
    sequence: 32,
    agent: "maria",
    type: "done",
    summary: "Maria leaves the fountain",
    content: "Maria closes her town day by the fountain edge.",
    locationHint: "square",
    subLocationId: "square_fountain_edge",
    activity: "closes build",
    routinePhase: "evening",
    status: "done",
  }),
  makeEvent({
    sequence: 33,
    agent: "klaus",
    type: "done",
    summary: "Klaus closes the stacks",
    content: "Klaus returns the final note to the library stacks.",
    locationHint: "library",
    subLocationId: "library_stacks",
    activity: "closes research",
    routinePhase: "evening",
    status: "done",
  }),
  makeEvent({
    sequence: 34,
    agent: "sam",
    type: "done",
    summary: "Sam closes review",
    content: "Sam leaves the final pass on the evidence wall.",
    locationHint: "review_room",
    subLocationId: "review_evidence_wall",
    activity: "closes review",
    routinePhase: "evening",
    status: "done",
  }),
  makeEvent({
    sequence: 35,
    agent: "mei",
    type: "done",
    summary: "Mei shelves the day",
    content: "Mei shelves the daily memory after reconciliation.",
    locationHint: "archive",
    subLocationId: "archive_shelves",
    activity: "closes memory",
    routinePhase: "evening",
    status: "done",
  }),
  makeEvent({
    sequence: 36,
    agent: "isabella",
    type: "done",
    summary: "Town day complete",
    content: "Isabella closes the daily plan back at the town hall table.",
    locationHint: "town_hall",
    subLocationId: "town_hall_table",
    activity: "closes day",
    routinePhase: "evening",
    status: "done",
  }),
];
